import { useMemo } from 'react'
import * as THREE from 'three'
const BED_LEN=3.2,BED_WID=1.8,LEG_H=0.33,FRAME_H=0.39,MATT_H=0.255,HEAD_H=1.35,HEAD_T=0.15
const FRAME_TOP=LEG_H+FRAME_H,MATT_TOP=FRAME_TOP+MATT_H,MATT_HALF_W=(BED_WID-0.06)/2
const ROOM_D=6.5,GRP_X=0.13+BED_LEN/2,GRP_Z=ROOM_D-0.03-BED_WID/2
const OVERHANG_Z=0.26,OVERHANG_FOOT=0.18,OVERHANG_FRONT=0.22,BLANK_HEAD_GAP=0.65
const BLANK_LEN=BED_LEN-BLANK_HEAD_GAP+OVERHANG_FOOT,BLANK_WID=(BED_WID-0.06)+OVERHANG_Z+OVERHANG_FRONT
const BLANK_XC=(BED_LEN/2+OVERHANG_FOOT/2)-BLANK_LEN/2,BLANK_ZC=(OVERHANG_FRONT-OVERHANG_Z)/2
const BLANK_BASE_Y=MATT_TOP+0.005,DRAPE_BOTTOM_Y=LEG_H+0.02,MIDDLE_LIFT=0.12
function woodTex(){const c=document.createElement('canvas');c.width=512;c.height=512;const ctx=c.getContext('2d')!;ctx.fillStyle='#c49a60';ctx.fillRect(0,0,512,512);for(let row=0;row<8;row++){const y=row*64,s=0.92+Math.random()*0.12;ctx.fillStyle=`rgb(${Math.min(255,Math.floor(196*s))},${Math.min(255,Math.floor(154*s))},${Math.min(255,Math.floor(96*s))})`;ctx.fillRect(0,y,512,64);ctx.strokeStyle='rgba(130,90,40,0.22)';ctx.lineWidth=1;for(let i=0;i<9;i++){const yl=y+Math.random()*64;ctx.beginPath();ctx.moveTo(0,yl);ctx.bezierCurveTo(150,yl+(Math.random()-.5)*10,360,yl+(Math.random()-.5)*10,512,yl+(Math.random()-.5)*6);ctx.stroke()};ctx.strokeStyle='rgba(100,65,25,0.4)';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(512,y);ctx.stroke()};const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(2,1);return t}
function fabricTex(color:string,rpt=8){const c=document.createElement('canvas');c.width=256;c.height=256;const ctx=c.getContext('2d')!;ctx.fillStyle=color;ctx.fillRect(0,0,256,256);ctx.strokeStyle='rgba(0,0,0,0.07)';ctx.lineWidth=1;for(let i=0;i<256;i+=4){ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(256,i);ctx.stroke();ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,256);ctx.stroke()};const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(rpt,rpt);return t}
function pillowGeo(){const s=new THREE.Shape();const hw=0.22,hh=0.38,r=0.07;s.moveTo(-hw+r,-hh);s.lineTo(hw-r,-hh);s.quadraticCurveTo(hw,-hh,hw,-hh+r);s.lineTo(hw,hh-r);s.quadraticCurveTo(hw,hh,hw-r,hh);s.lineTo(-hw+r,hh);s.quadraticCurveTo(-hw,hh,-hw,hh-r);s.lineTo(-hw,-hh+r);s.quadraticCurveTo(-hw,-hh,-hw+r,-hh);return new THREE.ExtrudeGeometry(s,{depth:0.13,bevelEnabled:true,bevelThickness:0.065,bevelSize:0.055,bevelSegments:5,curveSegments:16})}
function blanketGeo(len:number,wid:number,baseY:number,thick:number):THREE.BufferGeometry{
  const sX=56,sZ=44,hL=len/2,hW=wid/2,mZMin=-MATT_HALF_W-BLANK_ZC,mZMax=MATT_HALF_W-BLANK_ZC,footEdge=BED_LEN/2-BLANK_XC
  const sd=(t:number)=>t<0.15?t*t*4:0.06+(1-0.06)*((t2=>(t2*t2*(3-2*t2)))((t-0.15)/0.85))
  const dp=(x:number,z:number)=>{const u=(x+hL)/len,v=(z+hW)/wid,zOB=mZMin-z,zOF=z-mZMax,xOF2=x-footEdge;let dy=0;const onZ=z>=mZMin&&z<=mZMax,onX=x<=footEdge&&x>=-hL+0.1;if(onZ&&onX){const cx=(footEdge+(-hL+0.1))/2,cz=(mZMin+mZMax)/2,dx2=(x-cx)/(footEdge-cx+0.01),dz2=(z-cz)/(mZMax-cz+0.01),dd=dx2*dx2*0.6+dz2*dz2*0.6;dy+=MIDDLE_LIFT*Math.exp(-dd*1.5);dy+=Math.sin(u*Math.PI*3.2+0.7)*0.04+Math.sin(v*Math.PI*2.5+1.1)*0.022;dy+=Math.exp(-Math.pow((u-0.82)/0.10,2))*0.045;dy+=Math.exp(-Math.sqrt((u-0.38)**2*0.5+(v-0.6)**2*2)*12)*0.022;dy+=Math.exp(-Math.sqrt((u-0.25)**2+(v-0.22)**2)*10)*0.03};if(zOB>0){const t=Math.min(zOB/OVERHANG_Z,1);dy-=sd(t)*(BLANK_BASE_Y+MIDDLE_LIFT*0.3-DRAPE_BOTTOM_Y)}else if(onZ){dy-=Math.max(0,1-(z-mZMin)/0.06)*0.01};if(zOF>0){const t=Math.min(zOF/OVERHANG_FRONT,1);dy-=sd(t)*(BLANK_BASE_Y+MIDDLE_LIFT*0.3-DRAPE_BOTTOM_Y)}else if(onZ){dy-=Math.max(0,1-(mZMax-z)/0.06)*0.01};if(xOF2>0){const t=Math.min(xOF2/OVERHANG_FOOT,1);dy-=sd(t)*(BLANK_BASE_Y+MIDDLE_LIFT*0.3-DRAPE_BOTTOM_Y)*0.9};const cFD=Math.sqrt((x-hL)**2+(z-hW)**2);if(cFD<0.5)dy-=Math.exp(-cFD*4)*0.035;return dy}
  const pos:number[]=[],idx:number[]=[],uvs:number[]=[]
  for(let iz=0;iz<=sZ;iz++)for(let ix=0;ix<=sX;ix++){const x=-hL+(ix/sX)*len,z=-hW+(iz/sZ)*wid;pos.push(x,baseY+thick/2+dp(x,z),z);uvs.push((ix/sX)*3,(iz/sZ)*3)}
  const st=(sX+1)*(sZ+1)
  for(let iz=0;iz<=sZ;iz++)for(let ix=0;ix<=sX;ix++){const x=-hL+(ix/sX)*len,z=-hW+(iz/sZ)*wid;pos.push(x,baseY-thick/2+dp(x,z)*0.4,z);uvs.push((ix/sX)*3,(iz/sZ)*3)}
  for(let iz=0;iz<sZ;iz++)for(let ix=0;ix<sX;ix++){const a=iz*(sX+1)+ix,b=a+1,c=a+(sX+1),d=c+1;idx.push(a,c,b,b,c,d)}
  for(let iz=0;iz<sZ;iz++)for(let ix=0;ix<sX;ix++){const a=st+iz*(sX+1)+ix,b=a+1,c=a+(sX+1),d=c+1;idx.push(a,b,c,b,d,c)}
  for(let ix=0;ix<sX;ix++){const ta=ix,tb=ix+1,ba=st+ix,bb=st+ix+1;idx.push(ta,ba,tb,tb,ba,bb)}
  for(let ix=0;ix<sX;ix++){const ta=sZ*(sX+1)+ix,tb=ta+1,ba=st+sZ*(sX+1)+ix,bb=ba+1;idx.push(ta,tb,ba,tb,bb,ba)}
  for(let iz=0;iz<sZ;iz++){const ta=iz*(sX+1),tb=(iz+1)*(sX+1),ba=st+iz*(sX+1),bb=st+(iz+1)*(sX+1);idx.push(ta,ba,tb,tb,ba,bb)}
  for(let iz=0;iz<sZ;iz++){const ta=iz*(sX+1)+sX,tb=(iz+1)*(sX+1)+sX,ba=st+iz*(sX+1)+sX,bb=st+(iz+1)*(sX+1)+sX;idx.push(ta,tb,ba,tb,bb,ba)}
  const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uvs,2));g.setIndex(idx);g.computeVertexNormals();return g
}
export function Bed(){
  const wt=useMemo(()=>woodTex(),[]),mf=useMemo(()=>fabricTex('#f5f2ee',6),[]),bf=useMemo(()=>fabricTex('#6fa8d8',6),[]),pf=useMemo(()=>fabricTex('#faf6f2',5),[]),pg=useMemo(()=>pillowGeo(),[]),bg=useMemo(()=>blanketGeo(BLANK_LEN,BLANK_WID,BLANK_BASE_Y,0.05),[])
  const W=<meshStandardMaterial map={wt} roughness={0.58} metalness={0.05}/>
  return(<group position={[GRP_X,0,GRP_Z]}>{([[-BED_LEN/2+0.11,-BED_WID/2+0.11],[-BED_LEN/2+0.11,BED_WID/2-0.11],[BED_LEN/2-0.11,-BED_WID/2+0.11],[BED_LEN/2-0.11,BED_WID/2-0.11]] as [number,number][]).map(([lx,lz],i)=>(<mesh key={i} position={[lx,LEG_H/2,lz]} castShadow><boxGeometry args={[0.13,LEG_H,0.13]}/>{W}</mesh>))}<mesh position={[0,LEG_H+FRAME_H/2,0]} castShadow receiveShadow><boxGeometry args={[BED_LEN,FRAME_H,BED_WID]}/>{W}</mesh><group position={[-BED_LEN/2-HEAD_T/2,0,0]}><mesh position={[0,HEAD_H/2+LEG_H*0.5,0]} castShadow><boxGeometry args={[HEAD_T,HEAD_H,BED_WID+0.12]}/>{W}</mesh><mesh position={[0,HEAD_H+LEG_H*0.5+0.05,0]} castShadow><boxGeometry args={[HEAD_T+0.10,0.10,BED_WID+0.26]}/>{W}</mesh><mesh position={[0,LEG_H*0.5+0.05,0]} castShadow><boxGeometry args={[HEAD_T+0.10,0.09,BED_WID+0.26]}/>{W}</mesh></group><mesh position={[0,FRAME_TOP+MATT_H/2,0]} castShadow receiveShadow><boxGeometry args={[BED_LEN-0.06,MATT_H,BED_WID-0.06]}/><meshStandardMaterial map={mf} color="#f5f2ee" roughness={0.92}/></mesh><mesh geometry={bg} position={[BLANK_XC,0,BLANK_ZC]} castShadow receiveShadow><meshStandardMaterial map={bf} color="#6fa8d8" roughness={0.95} side={THREE.DoubleSide}/></mesh><mesh geometry={pg} position={[-BED_LEN/2+0.52,MATT_TOP+0.015,0]} rotation={[-Math.PI/2,0,0]} castShadow><meshStandardMaterial map={pf} color="#faf6f2" roughness={0.93}/></mesh></group>)
}
