import { useRef, useMemo } from 'react'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
const SURFACE_Y = 1.377
function cakeSideTex(base:string,accent:string):THREE.CanvasTexture{const W=512,H=192;const c=document.createElement('canvas');c.width=W;c.height=H;const ctx=c.getContext('2d')!;ctx.fillStyle=base;ctx.fillRect(0,0,W,H);[0.30,0.60].forEach(f=>{ctx.fillStyle='rgba(255,235,220,0.28)';ctx.fillRect(0,H*f-3,W,6)});ctx.fillStyle='#fff8f8';for(let x=0;x<W;x+=32){const dH=18+Math.sin(x*0.22+1.1)*9;ctx.beginPath();ctx.ellipse(x+16,0,13,dH,0,0,Math.PI);ctx.fill()};ctx.fillStyle=accent;for(let i=0;i<14;i++){const x=(i+0.5)*(W/14),y=H*0.55;ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill()};ctx.fillStyle=accent;for(let i=0;i<18;i++){const x=(i+0.5)*(W/18),y=H-10;ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fill()};return new THREE.CanvasTexture(c)}
function cakeTopTex(color:string):THREE.CanvasTexture{const W=256,H=256;const c=document.createElement('canvas');c.width=W;c.height=H;const ctx=c.getContext('2d')!;ctx.fillStyle='#fff8f8';ctx.fillRect(0,0,W,H);ctx.strokeStyle=color;ctx.lineWidth=7;ctx.lineCap='round';ctx.beginPath();for(let a=0;a<Math.PI*5;a+=0.08){const r=(a/(Math.PI*5))*110;const x=W/2+Math.cos(a)*r,y=H/2+Math.sin(a)*r;a===0?ctx.moveTo(x,y):ctx.lineTo(x,y)};ctx.stroke();return new THREE.CanvasTexture(c)}
function envBodyTex():THREE.CanvasTexture{const W=512,H=360;const c=document.createElement('canvas');c.width=W;c.height=H;const ctx=c.getContext('2d')!;ctx.fillStyle='#f4edd8';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#c0a860';ctx.lineWidth=2;ctx.strokeRect(5,5,W-10,H-10);ctx.strokeStyle='#b0a080';ctx.lineWidth=1.5;ctx.strokeRect(W-90,14,76,80);ctx.fillStyle='#e8dfc8';ctx.fillRect(W-89,15,74,78);ctx.fillStyle='#b0a080';[0.58,0.68,0.78].forEach(f=>ctx.fillRect(20,H*f,130,2.5));return new THREE.CanvasTexture(c)}
function envFlapTex():THREE.CanvasTexture{const W=512,H=280;const c=document.createElement('canvas');c.width=W;c.height=H;const ctx=c.getContext('2d')!;ctx.fillStyle='#ede6d0';ctx.fillRect(0,0,W,H);const g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,'rgba(255,250,235,0.6)');g.addColorStop(1,'rgba(200,185,150,0.25)');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);return new THREE.CanvasTexture(c)}
function vFlapGeo(W:number,D:number):THREE.BufferGeometry{const g=new THREE.BufferGeometry();const v=new Float32Array([-W/2,0,0,W/2,0,0,0,0,-D]);const n=new Float32Array([0,1,0,0,1,0,0,1,0]);const u=new Float32Array([0,1,1,1,0.5,0]);g.setAttribute('position',new THREE.BufferAttribute(v,3));g.setAttribute('normal',new THREE.BufferAttribute(n,3));g.setAttribute('uv',new THREE.BufferAttribute(u,2));g.setIndex([0,2,1]);return g}
function heartTex():THREE.CanvasTexture{const S=256;const c=document.createElement('canvas');c.width=S;c.height=S;const ctx=c.getContext('2d')!;ctx.clearRect(0,0,S,S);ctx.strokeStyle='rgba(255,255,255,0.95)';ctx.lineWidth=14;drawHeart(ctx,S/2,S/2+14,90,82);ctx.stroke();const g=ctx.createLinearGradient(0,40,0,220);g.addColorStop(0,'#ff5a7a');g.addColorStop(1,'#d6204a');ctx.fillStyle=g;drawHeart(ctx,S/2,S/2+14,90,82);ctx.fill();ctx.fillStyle='rgba(255,255,255,0.45)';ctx.beginPath();ctx.ellipse(S/2-30,S/2-12,26,15,-0.5,0,Math.PI*2);ctx.fill();return new THREE.CanvasTexture(c)}
function drawHeart(ctx:CanvasRenderingContext2D,cx:number,cy:number,rx:number,ry:number){ctx.beginPath();ctx.moveTo(cx,cy+ry*0.55);ctx.bezierCurveTo(cx-rx,cy-ry*0.35,cx-rx*0.55,cy-ry,cx,cy-ry*0.45);ctx.bezierCurveTo(cx+rx*0.55,cy-ry,cx+rx,cy-ry*0.35,cx,cy+ry*0.55);ctx.closePath()}
const CANDLE_COLORS=['#e85090','#5090e8','#e8b030','#50c878','#e85050','#8050e8','#50d0d0','#e87030','#c050c8','#60b840','#e8a050','#4060d8']
export function BirthdayCake(){
  const t1=useMemo(()=>cakeSideTex('#f4a8c0','#e85090'),[]),t2=useMemo(()=>cakeSideTex('#ffd0a0','#e8a030'),[]),tt=useMemo(()=>cakeTopTex('#e85090'),[])
  const BR=0.350,BH=0.28,TR=0.220,TH=0.22,FT=0.036,bs=SURFACE_Y,bt=bs+BH+FT,tb=bt,tT=tb+TH+FT
  const cps=useMemo(()=>{const p:{x:number,z:number,color:string}[]=[];for(let i=0;i<4;i++){const a=(i/4)*Math.PI*2;p.push({x:Math.cos(a)*0.076,z:Math.sin(a)*0.076,color:CANDLE_COLORS[i]})};for(let i=0;i<8;i++){const a=(i/8)*Math.PI*2+Math.PI/8;p.push({x:Math.cos(a)*0.144,z:Math.sin(a)*0.144,color:CANDLE_COLORS[i+4]})};return p},[])
  const cH=0.130,fY=tT+cH+0.028,fRef=useRef<THREE.Group>(null)
  useFrame(({clock})=>{if(!fRef.current)return;const t=clock.getElapsedTime();fRef.current.children.forEach((f,i)=>{f.scale.y=0.9+Math.sin(t*8+i*1.3)*0.12;f.scale.x=0.95+Math.cos(t*7+i*0.9)*0.06})})
  return(<group position={[-0.24,0,-0.08]}><mesh position={[0,bs+0.010,0]} castShadow><cylinderGeometry args={[BR*1.10,BR*1.14,0.020,40]}/><meshStandardMaterial color="#f0e8f8" roughness={0.6} metalness={0.12}/></mesh><mesh position={[0,bs+BH/2,0]} castShadow receiveShadow><cylinderGeometry args={[BR,BR*1.04,BH,40]}/><meshStandardMaterial map={t1} roughness={0.85}/></mesh><mesh position={[0,bs+BH+FT/2,0]} castShadow><cylinderGeometry args={[BR+0.022,BR+0.022,FT,40]}/><meshStandardMaterial map={tt} color="#fff4f8" roughness={0.8}/></mesh><mesh position={[0,tb+TH/2,0]} castShadow receiveShadow><cylinderGeometry args={[TR,TR*1.03,TH,34]}/><meshStandardMaterial map={t2} roughness={0.85}/></mesh><mesh position={[0,tb+TH+FT/2,0]} castShadow><cylinderGeometry args={[TR+0.018,TR+0.018,FT,34]}/><meshStandardMaterial map={tt} color="#fff4f8" roughness={0.8}/></mesh>{Array.from({length:12},(_,i)=>{const a=(i/12)*Math.PI*2;return(<mesh key={i} position={[Math.cos(a)*(BR-0.038),bt+0.022,Math.sin(a)*(BR-0.038)]} castShadow><sphereGeometry args={[0.028,8,8]}/><meshStandardMaterial color="#ffd0e8" roughness={0.85}/></mesh>)})}{Array.from({length:8},(_,i)=>{const a=(i/8)*Math.PI*2;return(<mesh key={i} position={[Math.cos(a)*(TR-0.028),tT+0.018,Math.sin(a)*(TR-0.028)]} castShadow><sphereGeometry args={[0.020,8,8]}/><meshStandardMaterial color="#ffe0a0" roughness={0.85}/></mesh>)})}{cps.map((cp,i)=>(<group key={i} position={[cp.x,tT,cp.z]}><mesh position={[0,cH/2,0]} castShadow><cylinderGeometry args={[0.014,0.014,cH,8]}/><meshStandardMaterial color={cp.color} roughness={0.6}/></mesh><mesh position={[0,0.006,0]}><cylinderGeometry args={[0.019,0.015,0.010,8]}/><meshStandardMaterial color={cp.color} roughness={0.8}/></mesh></group>))}<group ref={fRef}>{cps.map((cp,i)=>(<group key={i} position={[cp.x,fY,cp.z]}><mesh><sphereGeometry args={[0.018,6,8]}/><meshStandardMaterial color="#ff8800" emissive="#ff6600" emissiveIntensity={1.6} roughness={0.2} transparent opacity={0.92}/></mesh><mesh position={[0,0.008,0]} scale={[0.55,0.70,0.55]}><sphereGeometry args={[0.018,6,8]}/><meshStandardMaterial color="#ffee44" emissive="#ffcc00" emissiveIntensity={2.0} roughness={0.1} transparent opacity={0.95}/></mesh></group>))}</group><pointLight position={[0,fY+0.08,0]} color="#ffaa44" intensity={1.0} distance={3.5} decay={2}/></group>)
}
export function Envelope({open,onToggle}:{open:boolean;onToggle:()=>void}){
  const fRef=useRef<THREE.Group>(null),fA=useRef(0),EW=0.52,ED=0.36,ET=0.010,FD=ED*0.62
  const bt=useMemo(()=>envBodyTex(),[]),ft=useMemo(()=>envFlapTex(),[]),fg=useMemo(()=>vFlapGeo(EW,FD),[EW,FD]),ht=useMemo(()=>heartTex(),[])
  useFrame((_,delta)=>{const tg=open?Math.PI*0.78:0;const df=tg-fA.current;if(Math.abs(df)>0.001)fA.current+=df*Math.min(delta*5,1);if(fRef.current)fRef.current.rotation.x=fA.current})
  return(<group position={[0.92,SURFACE_Y,0.56]} rotation={[0,-0.18,0]} onClick={(e)=>{e.stopPropagation();onToggle()}} onPointerOver={()=>{document.body.style.cursor='pointer'}} onPointerOut={()=>{document.body.style.cursor='auto'}}><mesh position={[0,ET/2,0]}><boxGeometry args={[EW+0.18,ET+0.06,ED+0.18]}/><meshBasicMaterial transparent opacity={0} depthWrite={false}/></mesh><mesh position={[0,ET/2,0]} receiveShadow castShadow><boxGeometry args={[EW,ET,ED]}/><meshStandardMaterial map={bt} roughness={0.85}/></mesh><group ref={fRef} position={[0,ET+0.004,ED/2]}><mesh><primitive object={fg} attach="geometry"/><meshStandardMaterial map={ft} roughness={0.84} side={THREE.FrontSide} polygonOffset polygonOffsetFactor={-2} polygonOffsetUnits={-2}/></mesh><mesh><primitive object={fg} attach="geometry"/><meshStandardMaterial color="#ede6d0" roughness={0.86} side={THREE.BackSide}/></mesh><mesh position={[0,0.006,-FD*0.78]} rotation={[-Math.PI/2,0,Math.PI]} castShadow><planeGeometry args={[0.34,0.34]}/><meshStandardMaterial map={ht} transparent roughness={0.35} metalness={0.1} side={THREE.DoubleSide} polygonOffset polygonOffsetFactor={-6} polygonOffsetUnits={-6}/></mesh></group></group>)
}
