import { useMemo, useRef, useEffect } from 'react'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import { WIN_W, WIN_H, WIN_CENTER_X, WIN_CENTER_Y } from './Room'
function curtainTex(){const c=document.createElement('canvas');c.width=256;c.height=256;const ctx=c.getContext('2d')!;ctx.fillStyle='#4a7fd4';ctx.fillRect(0,0,256,256);ctx.fillStyle='#ffffff';for(let y=20;y<256;y+=40)for(let x=20;x<256;x+=40){const o=(y/40)%2===0?0:20;ctx.beginPath();ctx.arc(x+o,y,7,0,Math.PI*2);ctx.fill()};const t=new THREE.CanvasTexture(c);t.wrapS=t.wrapT=THREE.RepeatWrapping;return t}
export function Window({isNight,onClick}:{isNight:boolean;onClick:()=>void}){
  const ct=useMemo(()=>curtainTex(),[]),fd=0.12,ft=0.10,fc='#f5f0e8'
  const lRef=useRef<THREE.Mesh>(null),rRef=useRef<THREE.Mesh>(null),skyRef=useRef<THREE.MeshBasicMaterial>(null),glRef=useRef<THREE.MeshStandardMaterial[]>([])
  const tR=useRef(0),tgR=useRef(0)
  useEffect(()=>{tgR.current=isNight?1:0},[isNight])
  useFrame((state,delta)=>{const d=tgR.current-tR.current;if(Math.abs(d)>0.001)tR.current+=d*Math.min(delta*3,1);const t=tR.current;if(skyRef.current)skyRef.current.color.setRGB((168-t*165)/255,(216-t*208)/255,(240-t*224)/255);glRef.current.forEach(m=>{if(m)m.color.setRGB((200-t*194)/255,(232-t*220)/255,(248-t*222)/255)});const tm=state.clock.elapsedTime;if(lRef.current)lRef.current.rotation.y=0.02*Math.sin(tm*0.5);if(rRef.current)rRef.current.rotation.y=-0.02*Math.sin(tm*0.5)})
  const cW=0.8,cH=WIN_H+0.3
  return(<group position={[WIN_CENTER_X,WIN_CENTER_Y,0.06]}><mesh position={[0,0,-fd/2-0.01]}><planeGeometry args={[WIN_W,WIN_H]}/><meshBasicMaterial ref={skyRef} color="#a8d8f0"/></mesh><mesh onClick={(e)=>{e.stopPropagation();onClick()}} onPointerOver={()=>{document.body.style.cursor='pointer'}} onPointerOut={()=>{document.body.style.cursor='auto'}}><planeGeometry args={[WIN_W+cW*2,WIN_H+0.4]}/><meshBasicMaterial transparent opacity={0} depthWrite={false}/></mesh>{[{x:-WIN_W/4,y:WIN_H/4},{x:WIN_W/4,y:WIN_H/4},{x:-WIN_W/4,y:-WIN_H/4},{x:WIN_W/4,y:-WIN_H/4}].map((p,i)=>(<mesh key={i} position={[p.x,p.y,0]}><planeGeometry args={[WIN_W/2-ft,WIN_H/2-ft]}/><meshStandardMaterial ref={(m:THREE.MeshStandardMaterial)=>{if(m)glRef.current[i]=m}} color="#c8e8f8" transparent opacity={0.45} roughness={0.1} metalness={0.2} side={THREE.DoubleSide}/></mesh>))}{([{p:[0,WIN_H/2-ft/2,0],s:[WIN_W,ft,fd]},{p:[0,-WIN_H/2+ft/2,0],s:[WIN_W,ft,fd]},{p:[-WIN_W/2+ft/2,0,0],s:[ft,WIN_H,fd]},{p:[WIN_W/2-ft/2,0,0],s:[ft,WIN_H,fd]}] as {p:[number,number,number],s:[number,number,number]}[]).map((f,i)=>(<mesh key={i} position={f.p} castShadow><boxGeometry args={f.s}/><meshStandardMaterial color={fc} roughness={0.5} metalness={0.1}/></mesh>))}<mesh castShadow><boxGeometry args={[WIN_W-ft*2,0.06,fd]}/><meshStandardMaterial color={fc} roughness={0.5} metalness={0.1}/></mesh><mesh castShadow><boxGeometry args={[0.06,WIN_H-ft*2,fd]}/><meshStandardMaterial color={fc} roughness={0.5} metalness={0.1}/></mesh><mesh position={[0,-WIN_H/2-0.08,fd/2+0.05]} castShadow><boxGeometry args={[WIN_W+0.2,0.08,0.22]}/><meshStandardMaterial color={fc} roughness={0.5} metalness={0.1}/></mesh><mesh ref={lRef} position={[-WIN_W/2-cW/2+0.08,0,fd/2+0.02]} castShadow><planeGeometry args={[cW,cH]}/><meshStandardMaterial map={ct} roughness={0.85} side={THREE.DoubleSide}/></mesh><mesh ref={rRef} position={[WIN_W/2+cW/2-0.08,0,fd/2+0.02]} castShadow><planeGeometry args={[cW,cH]}/><meshStandardMaterial map={ct} roughness={0.85} side={THREE.DoubleSide}/></mesh><mesh position={[0,cH/2-0.05,fd/2+0.04]} rotation={[0,0,Math.PI/2]} castShadow><cylinderGeometry args={[0.04,0.04,WIN_W+cW*2,12]}/><meshStandardMaterial color="#c9a87a" roughness={0.4} metalness={0.3}/></mesh></group>)
}
